#服务启动端口
server:
  port: 8888

#设置配置文件是在本地还是git服务器上，设置本地配置文件具体位置
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

#配置注册服务地址
#eureka:
#  instance:
#    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
eureka:
  client:
    healthcheck:
      enables: true
    serviceUrl:
      #      defaultZone: http://${REGISTRY_SERVER_USERNAME:registry}:${REGISTRY_SERVER_PASSWORD:password}@localhost:${REGISTRY_SERVER_PORT:8762}/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # if you has depended on spring -boot-starter-security, the below setting for spring-boot-admin